# ConfigMap do flag-service
# Contém variáveis NÃO sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: flag-service
  labels:
    app: flag-service
    version: "1.0"
data:
  PORT: "8002"
  # DNS interno do auth-service (namespace = nome do serviço)
  AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8001"
