# ConfigMap do targeting-service
# Contém variáveis NÃO sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: targeting-service
  labels:
    app: targeting-service
    version: "1.0"
data:
  PORT: "8003"
  # DNS interno do auth-service (namespace = nome do serviço)
  AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8001"
