apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting-service
  labels:
    app: targeting-service
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
