apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
