# ConfigMap do auth-service
# Contém apenas variáveis NÃO sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-service
  labels:
    app: auth-service
    version: "1.0"
data:
  PORT: "8001"
