apiVersion: v2
name: flag-service
description: Flag Service - ToggleMaster Feature Flag System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flags
  - feature-flags
  - togglemaster
maintainers:
  - name: Tech Challenge Team
