#Este arquivo vai observar o deployment "evaluation-service" e mantém entre 1 e 5 réplicas.
#Escala para cima quando o CPU passar de 60% ou a memória passar de 70%. Sobe até 2 pods
#por minuto (para não estourar de uma vez) e desce 1 por vez com 120s de espera
#(para não ficar oscilando).
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evaluation-service-hpa
  namespace: evaluation-service
  labels:
    app: evaluation-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evaluation-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60