apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: evaluation-service
  labels:
    app: evaluation-service
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
